-- MySQL Script generated by MySQL Workbench
-- Sun Apr  5 11:40:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_project` DEFAULT CHARACTER SET utf8 ;
USE `db_project` ;

-- -----------------------------------------------------
-- Table `db_project`.`t_gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project`.`t_gender` (
  `d_index` INT NOT NULL,
  `d_sex` VARCHAR(2) NULL,
  PRIMARY KEY (`d_index`),
  UNIQUE INDEX `d_index_UNIQUE` (`d_index` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project`.`t_gemeente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project`.`t_gemeente` (
  `d_index` INT NOT NULL AUTO_INCREMENT,
  `d_postcode` SMALLINT(4) NULL,
  `d_gemeentenaam` VARCHAR(100) NULL,
  `d_land` VARCHAR(45) NULL,
  PRIMARY KEY (`d_index`),
  UNIQUE INDEX `d_index_UNIQUE` (`d_index` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project`.`t_aanspreekTitel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project`.`t_aanspreekTitel` (
  `d_index` INT NOT NULL,
  `d_aanspreekTitel` VARCHAR(10) NULL COMMENT 'Mevrouw,Mijnheer,Dhr',
  PRIMARY KEY (`d_index`),
  UNIQUE INDEX `d_index_UNIQUE` (`d_index` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project`.`t_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project`.`t_rol` (
  `d_index` INT NOT NULL,
  `d_rol` VARCHAR(45) NULL,
  PRIMARY KEY (`d_index`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project`.`t_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project`.`t_users` (
  `d_index` INT NOT NULL AUTO_INCREMENT,
  `d_naam` VARCHAR(45) NULL,
  `d_email` VARCHAR(100) NULL,
  `d_geboortedatum` DATE NULL,
  `d_voornaam` VARCHAR(45) NULL,
  `d_straat` VARCHAR(100) NULL,
  `d_huisNummer` CHAR(5) NULL,
  `d_telefoonnummer` VARCHAR(11) NULL,
  `d_datum` DATE NULL,
  `t_gender_d_index` INT NOT NULL,
  `t_adres_d_index` INT NOT NULL,
  `t_aanspreekTitel_d_index` INT NOT NULL,
  `t_rol_d_index` INT NOT NULL,
  PRIMARY KEY (`d_index`, `t_gender_d_index`, `t_adres_d_index`),
  UNIQUE INDEX `d_index_UNIQUE` (`d_index` ASC),
  INDEX `fk_t_users_t_gender_idx` (`t_gender_d_index` ASC),
  INDEX `fk_t_users_t_adres1_idx` (`t_adres_d_index` ASC),
  INDEX `fk_t_users_t_aanspreekTitel1_idx` (`t_aanspreekTitel_d_index` ASC),
  INDEX `fk_t_users_t_rol1_idx` (`t_rol_d_index` ASC),
  CONSTRAINT `fk_t_users_t_gender`
    FOREIGN KEY (`t_gender_d_index`)
    REFERENCES `db_project`.`t_gender` (`d_index`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_users_t_adres1`
    FOREIGN KEY (`t_adres_d_index`)
    REFERENCES `db_project`.`t_gemeente` (`d_index`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_users_t_aanspreekTitel1`
    FOREIGN KEY (`t_aanspreekTitel_d_index`)
    REFERENCES `db_project`.`t_aanspreekTitel` (`d_index`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_users_t_rol1`
    FOREIGN KEY (`t_rol_d_index`)
    REFERENCES `db_project`.`t_rol` (`d_index`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project`.`t_soort`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project`.`t_soort` (
  `d_index` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `d_soorNaam` VARCHAR(45) NULL,
  PRIMARY KEY (`d_index`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project`.`t_btw`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project`.`t_btw` (
  `d_index` INT NOT NULL AUTO_INCREMENT,
  `d_btw` VARCHAR(45) NULL,
  PRIMARY KEY (`d_index`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project`.`t_producten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project`.`t_producten` (
  `d_index` INT NOT NULL AUTO_INCREMENT,
  `d_productNaam` VARCHAR(100) NULL,
  `d_img` VARCHAR(100) NULL,
  `d_prijs` FLOAT NULL,
  `d_beschrijving` LONGTEXT NULL,
  `t_soort_d_index` INT UNSIGNED NOT NULL,
  `t_btw_d_index` INT NOT NULL,
  PRIMARY KEY (`d_index`, `t_soort_d_index`),
  UNIQUE INDEX `d_index_UNIQUE` (`d_index` ASC),
  INDEX `fk_t_producten_t_soort1_idx` (`t_soort_d_index` ASC),
  INDEX `fk_t_producten_t_btw1_idx` (`t_btw_d_index` ASC),
  CONSTRAINT `fk_t_producten_t_soort1`
    FOREIGN KEY (`t_soort_d_index`)
    REFERENCES `db_project`.`t_soort` (`d_index`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_producten_t_btw1`
    FOREIGN KEY (`t_btw_d_index`)
    REFERENCES `db_project`.`t_btw` (`d_index`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project`.`t_factuur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project`.`t_factuur` (
  `d_index` INT NOT NULL AUTO_INCREMENT,
  `t_users_d_index` INT NOT NULL,
  `d_productNaam` VARCHAR(100) NULL,
  `d_Prijs` VARCHAR(100) NULL,
  `d_datum` DATE NULL,
  `d_btw` VARCHAR(45) NULL,
  `d_factuurnummer` VARCHAR(100) NULL,
  `d_artieknummer` INT NULL,
  `d_aantal` INT NULL,
  PRIMARY KEY (`d_index`),
  UNIQUE INDEX `d_index_UNIQUE` (`d_index` ASC),
  INDEX `fk_t_order_t_users1_idx` (`t_users_d_index` ASC),
  CONSTRAINT `fk_t_order_t_users1`
    FOREIGN KEY (`t_users_d_index`)
    REFERENCES `db_project`.`t_users` (`d_index`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project`.`t_authentication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project`.`t_authentication` (
  `d_user` INT NOT NULL,
  `d_logon` VARCHAR(45) NULL,
  `d_paswoord` CHAR(64) NULL,
  `d_identifier` CHAR(64) NULL,
  `d_token` CHAR(64) NULL,
  `d_expire` BIGINT(20) NULL,
  `d_faultcntr` TINYINT(4) NULL,
  `d_timeOut` BIGINT(20) NULL,
  `d_resetKey` CHAR(64) NULL,
  `d_resetTime` BIGINT(20) NULL,
  `d_rol` TINYINT(4) NULL,
  PRIMARY KEY (`d_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project`.`t_authorised`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project`.`t_authorised` (
  `d_index` INT NOT NULL AUTO_INCREMENT,
  `d_schript` VARCHAR(100) NULL,
  `d_0` TINYINT(3) NULL,
  `d_1` TINYINT(3) NULL,
  `d_2` TINYINT(3) NULL,
  PRIMARY KEY (`d_index`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project`.`t_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project`.`t_menu` (
  `d_index` INT NOT NULL AUTO_INCREMENT,
  `d_item` VARCHAR(20) NULL,
  `d_link` VARCHAR(100) NULL,
  `d_volgorde` TINYINT(4) NULL,
  `d_menu` TINYINT(4) NULL,
  `d_0` TINYINT(3) NULL,
  `d_1` TINYINT(3) NULL,
  `d_2` TINYINT(3) NULL,
  PRIMARY KEY (`d_index`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project`.`t_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project`.`t_list` (
  `d_index` INT NOT NULL AUTO_INCREMENT,
  `t_producten_d_index` INT NOT NULL,
  `d_aantal` SMALLINT(4) NULL,
  PRIMARY KEY (`d_index`),
  INDEX `fk_t_list_t_producten1_idx` (`t_producten_d_index` ASC),
  CONSTRAINT `fk_t_list_t_producten1`
    FOREIGN KEY (`t_producten_d_index`)
    REFERENCES `db_project`.`t_producten` (`d_index`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project`.`t_bedrijf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_project`.`t_bedrijf` (
  `d_index` INT NOT NULL AUTO_INCREMENT,
  `d_naam` VARCHAR(60) NULL,
  `d_btw` VARCHAR(45) NULL,
  `d_straat` VARCHAR(50) NULL,
  `d_huisNummer` CHAR(5) NULL,
  `t_users_d_index` INT NOT NULL,
  `t_gemeente_d_index` INT NOT NULL,
  PRIMARY KEY (`d_index`),
  INDEX `fk_t_bedrijf_t_users1_idx` (`t_users_d_index` ASC),
  INDEX `fk_t_bedrijf_t_gemeente1_idx` (`t_gemeente_d_index` ASC),
  CONSTRAINT `fk_t_bedrijf_t_users1`
    FOREIGN KEY (`t_users_d_index`)
    REFERENCES `db_project`.`t_users` (`d_index`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_bedrijf_t_gemeente1`
    FOREIGN KEY (`t_gemeente_d_index`)
    REFERENCES `db_project`.`t_gemeente` (`d_index`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
